### ISSUE TITLE
Unable to see NFTs

### ISSUE THREAD

**Issue by sterlingcrispin** [OrderAndCh4oS/orderandchaos-tools#8]
hey thanks for your tool!

I tried to use it and its broken for my wallet though , I have 8 listed on HEN V1 and 8 listed on HEN V2 , they show up on nftbiker's tool but I cant cancel them there either.

On your website just nothing shows up, I saw this in the  javascript console

> get - swappable - objkts - by - wallet.js: 96 Error: field "hic_et_nunc_token"
not found in type: 'query_root': {
	"response": {
		"errors": [{
			"extensions": {
				"path": "$.selectionSet.hic_et_nunc_token",
				"code": "validation-failed"
			},
			"message": "field \"hic_et_nunc_token\" not found in type: 'query_root'"
		}],
		"status": 200,
		"headers": {
			"map": {
				"content-type": "application/json; charset=utf-8"
			}
		}
	},
	"request": {
		"query": "\n    query getObjktsByWallet($address: String!) {\n        hic_et_nunc_token(\n            where: {\n                token_holders: {\n                    quantity: {_gt: \"0\"},\n                    holder_id: {_eq: $address}\n                }\n            },\n            order_by: {id: desc}\n        ) {\n            id\n            creator_id\n            artifact_uri\n            display_uri\n            thumbnail_uri\n            timestamp\n            mime\n            title\n            description\n            supply\n            royalties\n            creator {\n                name\n            }\n            token_holders {\n                holder_id\n                quantity\n            }\n            swaps(where: {status: {_eq: \"0\"}}, order_by: {price: asc}) {\n                amount\n                amount_left\n                creator_id\n                price\n            }\n            trades {\n                timestamp\n                amount\n                swap {\n                    price\n                }\n            }\n        }\n    }\n",
		"variables": {
			"address": "tz1MjZyBDq5hPNReKNf6YTVYBJv3jWHuBqph"
		}
	}
}
at objectWithoutPropertiesLoose.js: 410: 11
at 2.901517 f1.chunk.js: 2: 652936
at Object.next(2.901517 f1.chunk.js: 2: 653041)
at o(2.901517 f1.chunk.js: 2: 651754)

**Comment by melMass** [comment]
Solved in #9 

You can see it there in the meantime: https://hicetnunc-batch-swapper-git-fork-melmass-main-orderandchaos.vercel.app/

**Comment by OrderAndCh4oS** [comment]
@sterlingcrispin Cheers for the heads up should be fixed now. 
@melMass Thanks so much for the PR!
